version: "3.5"

networks:
  servicenet:
    driver: overlay
    ipam:
      config:
        -
          subnet: 10.0.9.0/24

services:
  redis:
    image: redis/redis-stack:6.2.2-v4
    #command: redis-cli --save 20 1 --loglevel warning --appendonly yes --protected-mode no
    volumes:
      - "../data/redis:/data"
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: ingress
      - target: 8001
        published: 8001
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
  sender:
    image: 'hostingdemo'
    environment:
      HydraConfig__Hydra__ServiceType: sender
      HydraConfig__Hydra__ServiceName: sender-svcs
    depends_on:
      - redis
  queuer:
    image: 'hostingdemo'
    environment:
      HydraConfig__Hydra__ServiceType: queuer
      HydraConfig__Hydra__ServiceName: queuer-svcs
    depends_on:
      - redis




