version: "3.5"

services:
  redis:
    image: redis/redis-stack:6.2.2-v4
    #command: redis-cli --save 20 1 --loglevel warning --appendonly yes --protected-mode no
    volumes:
      - "../data/redis:/data"
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: ingress
      - target: 8001
        published: 8001
        protocol: tcp
        mode: ingress
  sender:
     image: 'hostingdemo'
     environment:
       Hydra__ServiceType: sender
       Hydra__ServiceName: sender-svcs
     depends_on:
       - redis
  queuer:
    image: 'hostingdemo'
    environment:
      Hydra__ServiceType: queuer
      Hydra__ServiceName: queuer-svcs
    depends_on:
      - redis